<?php require 'templates/header.phtml';?>
<main class="main-administrar">
    <div class="administrar-info">
        <div class="logo-info">
            <i class="fa-solid fa-info fa-sm"></i>
        </div>
        <h4>Aclaración:</h4>
        <p>Los botones de arriba de los formularios cambian las funciones de los mismos. Consultar la tabla del final de la pagina para saber el id del producto o categoria que desea editar o eliminar.</p>
    </div>
</main>

<div class="form-type">
    <input class="btns-admin" type="button" value="Editar" number="1">
    <input class="btns-admin" type="button" value="Agregar" number="2">
    <input class="btns-admin" type="button" value="Eliminar" number="3">
</div>

<form action="agregarProducto" method="POST" class="form" id="form-productos">
    <p class="form-title" id="form-title-productos">Agregar Producto</p>

    <div class="noMostrar" id="select-ids-productos">
        <label for="id">Seleccione el id de un producto</label>
        <select name="id">
            <?php foreach ($products as $product) : ?>
                <option value="<?= $product->id_producto ?>"><?= $product->id_producto ?></option>
            <?php endforeach ?>
        </select>
    </div>

    <div class="" id="cont-form-productos">
        <div class="form-input__container">
            <label>Nombre del producto</label>
            <input name="nombre_producto" type="text" class="form-control">
        </div>

        <div class="form-input__container">
            <label>Precio</label>
            <input type="number" name="precio" class="form-control"></input>
        </div>

        <div class="form-select__conteiner select-width">
            <label>Categoria</label>
            <select required name="id_categoria" class="form-control">
                <?php foreach ($categorys as $category) : ?>
                    <option value="<?= $category->id_categoria ?>"><?= $category->id_categoria ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <button action="administrar" type="submit" class="form-submit" id="btn-submit-productos">Enviar</button>
</form>

<div class="form-type">
    <input class="btns-admin" type="button" value="Editar" number="4">
    <input class="btns-admin" type="button" value="Agregar" number="5">
    <input class="btns-admin" type="button" value="Eliminar" number="6">
</div>

<form action="agregarCategoria" class="form" method="POST" id="form-categorias">
    <p class="form-title" id="form-title-categorias">Agregar Categoria</p>

    <div class="noMostrar" id="select-ids-categorias">
        <label for="id_categoria">Seleccione una categoria</label>

        <p id="p-eliminar-producto">Recuerde que para eliminar la catogoria, esta no debe tener productos.</p>
        <select name="id_categoria">
            <?php foreach ($categorys as $category) : ?>
                <option value="<?= $category->id_categoria ?>"><?= $category->nombre ?></option>
            <?php endforeach ?>
        </select>
    </div>

    <div class="" id="cont-form-categorias">
        <div class="form-input__container">
            <label>Nombre de la categoria</label>
            <input name="nombre" type="text" class="form-control">
        </div>
    </div>

    <button action="administrar" type="submit" class="form-submit" id="btn-submit-categorias">Enviar</button>
</form>

<div class="tabla-container">
    <h3>Info de los Productos</h3>
    <p>Tabla para mostrar información y eliminar productos de la base de datos</p>
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Producto</th>
                <th>Precio</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td><?= $product->id_producto ?></td>
                    <td><?= $product->nombre_producto ?></td>
                    <td>$<?= $product->precio ?></td>
                    <td>
                        <?php
                        $i = 0;
                        $var = false;
                        while ($var == false && $i < count($categorys)) {
                            if ($product->id_categoria == $categorys[$i]->id_categoria) {
                                $var = true;
                                echo "(" . $categorys[$i]->id_categoria . ")" . $categorys[$i]->nombre;
                            }
                            $i++;
                        } ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
</main>
<script src="js/administrar.js"></script>
<script src="js/main.js"></script>
</body>

</html>