<?php require 'templates/header.phtml';?>
<main class="main-form__inicioSesion">
    <form action="crearCuenta" method="POST" class="form">
        
        <p class="form-title">registrese a su cuenta</p>

        <div class="form-input__container">
            <input name="email_register" placeholder="   Email">
        </div>

        <div class="form-input__container">
            <input required name="contraseña" type="password" placeholder="    Contraseña">
        </div>


        <button type="submit" class="form-submit">
            registrar
        </button>
</main>
<?php require 'templates/footer.phtml';?>