<div class="container-cards">

    <?php foreach ($products as $product) : ?>
        <div class="card">
            <div class="card-header">
                <?php
                $i = 0;
                $var = false;
                while ($var == false && $i < count($categorys)) {
                    if ($product->id_categoria == $categorys[$i]->id_categoria) {
                        $var = true; ?>
                        <p><?= $categorys[$i]->nombre ?></p>
                <?php
                    }
                    $i++;
                } ?>
            </div>
            <div class="card-img">
                <img class="img-card" src="img/<?=$product->nombre_producto?>.jpg" alt="<?= $product->nombre_producto ?>" style="width:300px; height:300px;">
            </div>
            <div class="card-body">
                <h5 class="card-price">$<?=$product->precio?></h5>
                <h5 class="card-title"><?=$product->nombre_producto?></h5>
                <button class="btn btn-primary">Comprar</button>
            </div>
        </div>
    <?php endforeach ?>
</div>
<?php require('templates/footer.phtml'); ?>